### ISSUE TITLE
show traffic

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_fall_2020#20]

**Comment by claesmk** [comment]
This is sample discussion about show traffic.  I'd like a pointer to more documentation about what each field means @claesmk  can you help me with that?

**Comment by m-maque96** [comment]
Good afternoon, I am confused on what Group 5 is supposed to be doing for this sprint. Can you please guide us step by step for what to do for this sprint? @claesmk

**Comment by claesmk** [comment]
Group 5 should create two new issues (user-stories) for sprint 1 - "Create stub function for show traffic" and "Create stub function for show interface" You should then apply the sprint 1 milestone and also select a size label.  Then from your fork you should add the stub functions, run the unit-test, and submit a pull request as we showed in the demo.  Was Dr Roy able to post the recording with this demonstrated?

**Comment by m-maque96** [comment]
Yes, he did.
