### ISSUE TITLE
Create stub function for show ipsec stats

### ISSUE THREAD

**Issue by JustinNoland24** [NCATComp410/comp410_fall_2020#28]
Work required for sprint 1 reference #18

**Comment by claesmk** [comment]
@JustinNoland24 this looks good so far.  Looks like all you need to do is sync your fork and then you'll be able to do a pull request.  Let me know if you need any help with that.

**Comment by JustinNoland24** [comment]
Hey Mike, So I see that I have a merging issue and I was trying to pull requests. Before I tried to pull request though, I was trying to sync my fork your project repo. And I was just confused on how the merging works. I saw that in some files the changes made of other students but when I merge I don't see those changes of other students on my local computer. Why is that? and how can I fix this merging issue?

**Comment by JustinNoland24** [comment]
Hey @claesmk So I see that I have a merging issue and I was trying to pull requests. Before I tried to pull request though, I was trying to sync my fork with your project repo. And I was just confused on how the merging works. I saw that in some files of your repo the changes made by other students, but when I merge with your project repo I don't see those changes of other students on my local computer. Why is that? and how can I fix this merging issue?

**Comment by claesmk** [comment]
Hi @JustinNoland24 please take a look at (3) in [this](https://github.com/orgs/NCATComp410/teams/comp410fall2020class/discussions/9) post which has a link for how to sync a fork from the command line.  If you are using PyCharm you can accomplish the same thing by merging upstream/dev into current.  Here is what it looks like when I do it from the comment line:

First note that I have cloned my fork (which is origin) and also created a remote for the master repo
```
git remote -v
origin  https://github.com/claesmk/comp410_fall_2020.git (fetch)
origin  https://github.com/claesmk/comp410_fall_2020.git (push)
upstream        https://github.com/NCATComp410/comp410_fall_2020.git (fetch)
upstream        https://github.com/NCATComp410/comp410_fall_2020.git (push)
```

Next I get the latest from upstream:
```
git fetch upstream
remote: Enumerating objects: 68, done.
remote: Counting objects: 100% (66/66), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 44 (delta 25), reused 39 (delta 22), pack-reused 0
Unpacking objects: 100% (44/44), done.
From https://github.com/NCATComp410/comp410_fall_2020
   6567524..bd60231  dev        -> upstream/dev
```

Next I perform the merge - remember we're working from the dev branch - 
```
git merge upstream/dev
Updating 6567524..bd60231
Fast-forward
 asa_parser/src/asa_parse.py     | 8 ++++++++
 asa_parser/tests/test_parser.py | 6 ++++++
 demo.py                         | 8 +++++---
 3 files changed, 19 insertions(+), 3 deletions(-)
```

Now I have the latest in my local repo on my computer (I don't have any new changes).
