### ISSUE TITLE
Create stub function for show interface

### ISSUE THREAD

**Issue by m-maque96** [NCATComp410/comp410_fall_2020#33]
Work for sprint1 - master issue is #19

**Comment by m-maque96** [comment]
@claesmk Good evening Mike. I am trying to start up and complete the stub function for show interface. I am up to the implement the stub function. I wanted to see if I am setting up pycharm correctly. I attached the window of the new project.
![pycharm set up](https://user-images.githubusercontent.com/31222795/96385845-80308f80-1164-11eb-9a2d-b580448cf921.PNG)

**Comment by claesmk** [comment]
I'm assuming you already installed anaconda and created the py38 venv as described in the release notes.  If so, then you can follow the [JetBrains PyCharm instructions](https://www.jetbrains.com/help/pycharm/conda-support-creating-conda-virtual-environment.html) to use an existing conda env. Let me know if you have trouble and need to setup a Zoom call.

**Comment by claesmk** [comment]
When you do this you should see your py38 env pop up as a choice in the existing interpreter box.

**Comment by m-maque96** [comment]
I finished implementing the stub function for show interface.

**Comment by m-maque96** [comment]
Mike helped issue with PyCharm issues and git bash issue.

**Comment by m-maque96** [comment]
Once I added stub function and added the print show interface, committed my changes, merged, and pushed. How do I this step: 3) Sync your fork to the master repo. @claesmk

**Comment by claesmk** [comment]
You are 4 commits ahead, 3 commits behind NCATComp410:dev so you need to sync your fork and push again.  After you've done that you'll need to submit a pull request - just browse to your [repo](https://github.com/m-maque96/comp410_fall_2020) and click pull request

**Comment by m-maque96** [comment]
For some reason when I tried to pushed, a window popped up saying to login to github, and I tried to log in, but it kept loading and did not do anything @claesmk

**Comment by claesmk** [comment]
Try
```
git push
```
from your terminal window see if you can login that way

**Comment by m-maque96** [comment]
dmeyer3691 Merge pull request #56 from m-maque96/dev
