### ISSUE TITLE
show process

### ISSUE THREAD

**Issue by claesmk** [NCATComp410/comp410_fall_2020#5]

**Comment by Aaronandrew** [comment]
https://github.com/NCATComp410/comp410_fall_2020/pull/60#issue-508587843

**Comment by Aaronandrew** [comment]
https://github.com/NCATComp410/comp410_fall_2020/pull/60#issue-508587843

**Comment by Aaronandrew** [comment]
pythonLocation: /opt/hostedtoolcache/Python/3.8.6/x64
    LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.8.6/x64/lib
============================= test session starts ==============================
platform linux -- Python 3.8.6, pytest-6.1.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/runner/work/comp410_fall_2020/comp410_fall_2020
collected 10 items

asa_parser/tests/test_parser.py ..........                               [100%]

============================== 10 passed in 0.08s ==============================
