### ISSUE TITLE
Implement the stub function show traffic

### ISSUE THREAD

**Issue by m-maque96** [NCATComp410/comp410_fall_2020#57]
Work for sprint1 - master issue is #20

**Comment by m-maque96** [comment]
Updated asa_parser.py with stub function for show traffic 
![updated asaparser with show traffic](https://user-images.githubusercontent.com/31222795/96674195-37c8cb80-1336-11eb-9ca4-5c8b7fb4ee16.PNG)

**Comment by m-maque96** [comment]
Perform pytest and 9 passed in 0.35s 
![pytest after adding show traffic stub func](https://user-images.githubusercontent.com/31222795/96674071-f46e5d00-1335-11eb-9b7c-020793debdcc.PNG)

**Comment by m-maque96** [comment]
Performed Demo after updating with show traffic stub func. Screenshot of result below
![Inkedshow traffic demo_LI](https://user-images.githubusercontent.com/31222795/96674412-c0476c00-1336-11eb-9887-1aa9078bd1fe.jpg)

**Comment by m-maque96** [comment]
Included the show traffic stub function with the show interface stub function and included it with my work, within the same issue as the implement the stub function for show interface (#33). @dmeyer3691  @claesmk

**Comment by claesmk** [comment]
OK I linked this issue to the show interface pull request.  In the future, best practice is to make the pull requests separate so they can be tracked separately.  No need to re-do anything, just a comment for future improvement.

**Comment by m-maque96** [comment]
I understand. I made the mistake of not closing that issue before making this one. Thank you very much.
