### ISSUE TITLE
Implement Unit Test for show interface

### ISSUE THREAD

**Issue by m-maque96** [NCATComp410/comp410_fall_2020#85]

**Comment by m-maque96** [comment]
@claesmk I am getting error for my show interface unit test. I am not sure why I am getting an error. 
![interface ERROR](https://user-images.githubusercontent.com/31222795/98393243-0420bd80-2027-11eb-88c1-2ca84e872793.PNG)
![first line of interface](https://user-images.githubusercontent.com/31222795/98393253-07b44480-2027-11eb-8956-c6ae82eec875.PNG)

**Comment by claesmk** [comment]
The problem is the quotes - it's the way json.dumps handles them.  You should escape them like this:
```
self.assertIn('["Interface Internal-Data0/1 \\"\\", is up, line protocol is up"', result)
```
Then your unit-test should pass ok

**Comment by m-maque96** [comment]
Oh, I gotcha. I felt like that was the issue. Thank you
